### ISSUE TITLE
Decode error

### ISSUE THREAD

**Issue by saiberz** [alco/hashids-elixir#11]
Elixir 1.7.1
hashids 2.0.4

Decode is returning same value for different inputs(most of them substrings of the encoded value)

```elixir
s = Hashids.new([
     salt: "dummie salt",
     min_len: 16,
  ])

c1 = Hashids.encode(s, 1)
# "6oO7xzWl6bZvKm9X"

Hashids.decode(s, "6oO7xzWl6bZvKm9X")
# {:ok, [1]}
Hashids.decode(s, "6oO7xzWl6bZvKm9k")
# {:ok, [1]}
Hashids.decode(s, "6oO7xzWl6bZvKsadjsnd22e2d1")
# {:ok, [1]}
Hashids.decode(s, "6oO7xzWl6bZvKm91")
# {:ok, [1]}
Hashids.decode(s, "6oO7xzWl6bZvKm9")
# {:ok, [1]}
Hashids.decode(s, "6oO7xzWl6bZvKm")
# {:ok, [1]}
Hashids.decode(s, "6oO7xzWl6bZvK")
# {:ok, [1]}
Hashids.decode(s, "6oO7xzWl6bZv")
# {:ok, [1]}
Hashids.decode(s, "6oO7xzWl6bZ")
# {:ok, [1]}
Hashids.decode(s, "6oO7xzWl6b")
# {:ok, [1]}
```

Is there any way I can help to solve this?

**Comment by alco** [comment]
This is a side effect of how the algorithm works compounded by the fact you have specified `min_len: 16`. If you omit that option, the algorithm returns a minimal string for any input ID and changing that string will most likely change the number you'll get after decoding it.

But when the minimal encoding is shorter than `min_len`, redundant characters are added to it to extend the output. In the end, this extended output can be changed up quite a bit and still decode to the same number.

As a sanity check I suggest encoding the number you get from decoding a string and seeing if you get the same string. If not, then the initial string must have been tampered with.

**Comment by marcelfahle** [comment]
Oh man @alco, that is good information..  Because for the last two days I'm wrestling with this. Quick example:

```elixir
s = Hashids.new(alphabet: "0123456789abcdefghjkmnpqrstvwxyz", min_len: 5, salt: "plbla bla bla")
%Hashids{
  a_len: 22,
  alphabet: '9g538wr4mkn7a6jdypzvxq',
  g_len: 2,
  guards: 'eb',
  min_len: 5,
  s_len: 8,
  salt: 'plbla bla bla',
  seps: 'fsthc012'
}

Hashids.decode!(s, "abcde")
'\b'
Hashids.decode!(s, "abcdef")
'\b'
Hashids.decode!(s, "abcdefg")
'\b'
Hashids.decode!(s, "abcdefghj")
'\b'

```

The result being the ascii code for the number 8, which is a valid ID in my DB. 

For me to understand: "abcdef" is not a valid string, so the algorithm makes it valid, which in this weird case always results in 8?

Here's the other thing I don't understand, when I add my alphabet as `0123456789abcdefghjkmnpqrstvwxyz`, why does it return it as `9g538wr4mkn7a6jdypzvxq`.

I'm sure it's me just using it wrong, but my customer told me yesterday "yo, whatever string I put in the slug, I always get record # 8 from the DB 😬 

I'm on v 2.0.4 and my results here are not consistent with the JS version

Anyway, thanks for your work, love the library!

**Comment by alco** [comment]
Hi @marcelfahle.

Thanks for taking the time to describe your issue in detail.

The alphabet that you pass to `Hashids.new()` is shuffled according to the internal hashids algorithm, don't worry about it looking different when inspected.

Regarding the decoding, to make sure you're getting a valid string, you have to take the number returned from `Hashids.decode()` and pass it through `encode()`, then compare the returned string with the one you got from the user. The hashids algorithm is not that sophisticated, so it is expected that different strings may be decoded into the same number.

As for why you're getting an empty array from the JavaScript implementation, it may be that the library is performing the check I've described internally and returns an empty result if the two strings it compared did not match. This might be a good addition to my library as well; I may have skipped it originally because I didn't want to force this additional operation on the user of the library but I don't remember for sure.

**Comment by alco** [comment]
Closing as inactive.
