### ISSUE TITLE
Strings vs. char lists

### ISSUE THREAD

**Issue by whatyouhide** [alco/hashids-elixir#2]
Hey there,

I think this library (well, the whole Hashids idea) is great. One thing that in my opinion could be improved in this Elixir implementation is getting rid of char lists: to me it looks like char lists in Elixir are mostly an Erlang heritage and it looks like strings are far more common.

Do you think there would be any downsides in using strings? Or did you choose to use char lists for a particular reason?

If we want to go further with this, we could just deprecate char lists (but continue to support them since the hex package is a 1.0).

I'm looking forward to hear your thoughts!

**Comment by alco** [comment]
Hi @whatyouhide.

There is no particular reason for why charlists are used in the `encode` and `decode` functions, it's just what is used in the implementation. I think it would be nice for those functions to support iodata, not just binaries. The reasoning for this is that generated "hashes" are normally sent to some IO system which accepts iodata most of the time and decoding is also performed on the data read from some IO source which we should not limit to a particular type if we can accept iodata.

As for the alphabet that is passed to `new()`, this is a trickier choice. On the one hand, making it a list could allow using any kind of characters including invalid code points. We could leave it up to the user to decide how to pass the generated "hash" on the wire if they wish to use a weird alphabet. On the other hand, it would be much simpler to limit the alphabet to a set of valid Unicode characters so that all of the generated hashes are automatically encodable/decodable by the standard IO mechanisms.

The second option is the most sensible one, I think. I also think it would be OK to keep it as a list since most of the time it should be a literal, so it doesn't make much difference. Although we should also research the other implementations and see how they handle exotic code points or surrogate pairs if they're using strings for the alphabet.

**Comment by whatyouhide** [comment]
Hey @alco,

regarding the alphabet I agree, it makes sense to live it as a character list since most of the times it's going to be a literal.

The output of `encode` and `decode` could be `iodata`, but I think this would be mostly confusing to newcomers. Maybe making that output a string would just make things easier in most situations. Maybe `decode` could accept `iodata`, but I'd make `encode` always return binaries.

If we (I mean, you :stuck_out_tongue_winking_eye:) decide to go for binaries, probably using a binary salt would make more sense too just for consistency.

Then again, if we go with binaries for `encode`/`decode` and the salt, we may as well use a binary for the alphabet and just use `String.to_char_list/1`. I may be missing something here though.

What do you think?

**Comment by alco** [comment]
After thinking about it some more, I think the following should be changed:

  * `salt` and `alphabet` should both be strings. Internally they will be converted to char lists and the docs will say that the _codepoints_ from both are used in the calculation of the hash. This is how the original JavaScript implementation also works.

  * `decode` will take iodata

  * `encode` will return either a list or a binary. I will benchmark it and see which performs better. The type signature can say iodata as well to indicate the intended usage. I don't see a particular downside to returning iodata. It can be just as easily interpolated into strings (URLs, for example) as strings.

**Comment by alco** [comment]
The changes will also be backwards compatible: internally, Hashids will keep accepting char lists for salt and alphabet. I'll just update the docs to only mention strings.

**Comment by whatyouhide** [comment]
@alco hey there, your plan sounds good and very solid. Do you need any help on the code? I can try :) Ping me if you do!

**Comment by alco** [comment]
My mistake, char lists are not actually compatible with iodata. So I decided to roll out a 2.0.0 release instead.

Thanks for the discussion!
